using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace CsWSC.Generators;

/// <summary>
/// ScriptGlobals の public メンバーに、UWSC 風の全部大文字の別名 (補完には出さない) を生成する。
/// </summary>
[Generator]
public sealed class UpperAliasGenerator : IIncrementalGenerator
{
    private const string TargetType = "CsWSC.ScriptGlobals";
    private const string Hidden = "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";

    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var source = context.CompilationProvider.Select((c, _) =>
        {
            var type = c.GetTypeByMetadataName(TargetType);
            return type is null ? null : Generate(type);
        });
        context.RegisterSourceOutput(source, (spc, code) =>
        {
            if (code is not null) spc.AddSource("ScriptGlobals.Upper.g.cs", code);
        });
    }

    private static string Generate(INamedTypeSymbol type)
    {
        var existing = type.GetMembers().Select(m => m.Name).ToImmutableHashSet();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {type.ContainingNamespace.ToDisplayString()};");
        sb.AppendLine();
        sb.AppendLine($"partial class {type.Name}");
        sb.AppendLine("{");

        foreach (var member in type.GetMembers())
        {
            if (member.DeclaredAccessibility != Accessibility.Public || member.IsStatic || member.IsImplicitlyDeclared) continue;
            var upper = member.Name.ToUpperInvariant();
            if (upper == member.Name || existing.Contains(upper)) continue;

            switch (member)
            {
                case IPropertySymbol { IsIndexer: false, GetMethod: { DeclaredAccessibility: Accessibility.Public } } p:
                    sb.AppendLine($"    {Hidden} public {p.Type.ToDisplayString(TypeFormat)} {upper} => {p.Name};");
                    break;
                case IMethodSymbol { MethodKind: MethodKind.Ordinary, IsGenericMethod: false } m:
                    var parameters = string.Join(", ", m.Parameters.Select(FormatParameter));
                    var arguments = string.Join(", ", m.Parameters.Select(a => "@" + a.Name));
                    var ret = m.ReturnsVoid ? "void" : m.ReturnType.ToDisplayString(TypeFormat);
                    sb.AppendLine($"    {Hidden} public {ret} {upper}({parameters}) => {m.Name}({arguments});");
                    break;
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string FormatParameter(IParameterSymbol p)
    {
        var text = $"{(p.IsParams ? "params " : "")}{p.Type.ToDisplayString(TypeFormat)} @{p.Name}";
        return p.HasExplicitDefaultValue ? $"{text} = {FormatDefault(p)}" : text;
    }

    private static string FormatDefault(IParameterSymbol p)
    {
        var value = p.ExplicitDefaultValue;
        if (value is null) return "default";
        var type = p.Type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } n ? n.TypeArguments[0] : p.Type;
        var literal = SymbolDisplay.FormatPrimitive(value, quoteStrings: true, useHexadecimalNumbers: false);
        if (value is float) literal += "f";
        return type.TypeKind == TypeKind.Enum ? $"({type.ToDisplayString(TypeFormat)})({literal})" : literal;
    }
}
